# fly.toml app configuration file generated for llm-opendata-streamlit on 2025-06-06T01:39:08+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'llm-opendata-streamlit'
primary_region = 'hkg'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'
  wait_timeout = '300ns'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '16gb'
  cpu_kind = 'shared'
  cpus = 8
